### ISSUE TITLE
XDocument and IconLayout

### ISSUE THREAD

**Issue by diavolodeejay** [0xFireball/MK.MobileDevice#3]
How i can upload an XDocument to SET an iconlayout? 
I can't find anything that can help me to convert the XDocument to a IntPtr.
Asking here because i can't find a contact to the mantainer :disappointed:

**Comment by 0xFireball** [comment]
Sure, you can ask questions through issues. I was working on it, but it did not work easily. I am rather busy for the next few months, and will look into it soon. Why don't you play around and implement it yourself and pull request? You can look through the code for examples in writing your own binding.

**Comment by 0xFireball** [comment]
As for converting XDocuments to an IntPtr, be aware that it first needs to be a valid PList. The PList functionality does exist; however, it was not visible due to a mistake. It has been fixed in the latest commit, you can find this in the `LibPlist` class in the namespace `MK.MobileDevice`. Please follow up if you still cannot solve your problem.

**Comment by 0xFireball** [comment]
Can I close this issue? It has been inactive for quite a while and we have resolved the problem right?
